server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/EFOOTBALL   # ← nombre de tu BD
    username: caza_user                                # ← tu usuario de pgAdmin
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB      # límite por archivo (por defecto era 1MB)
      max-request-size: 15MB   # límite total de la petición

application:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 86400000
  gemini:
    api-key: ${GEMINI_API_KEY:your-gemini-api-key-here}
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    com.caza: INFO
